/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { XarbMintUpgradeableTestV2 } from "./XarbMintUpgradeableTestV2";
export type { XarbSwapUpgradeableTestV2 } from "./XarbSwapUpgradeableTestV2";
