/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { XarbMintUpgradeableTestV2__factory } from "./XarbMintUpgradeableTestV2__factory";
export { XarbSwapUpgradeableTestV2__factory } from "./XarbSwapUpgradeableTestV2__factory";
